<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472</TargetFrameworks>
    <RootNamespace>SIL.BuildTasks.Tests.Helper</RootNamespace>
    <AssemblyTitle>SIL.BuildTasks.Tests.Helper</AssemblyTitle>
    <OutputPath>bin</OutputPath>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <!-- Don't update NUnit to 3.x - that'll require refactoring the NUnitTests fixture! -->
    <PackageReference Include="NUnit" Version="2.6.5" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="app.config" Condition="'$(OS)'=='Windows_NT'" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>